export const progLanguages = [
  "CSharp.png",
  "CSS3.png",
  "Discord.js.png",
  "Express.png",
  "HTML5.png",
  "JavaScript.png",
  "Jest.png",
  "JSON.png",
  "Next.js.png",
  "Node.js.png",
  "Nuxt-JS.png",
  "PHP.png",
  "Python.png",
  "React.png",
  "Sass.png",
  "Symfony.png",
  "Tailwind-CSS.png",
  "Three.js.png",
  "TypeScript.png",
  "Vue.js.png",
  "WordPress.png",
];

export const tools = [
  "Adobe-Illustrator.png",
  "Blender.png",
  "Figma.png",
  "Git.png",
  "Jira.png",
  "MongoDB.png",
  "SQLite.png",
  "Trello.png",
  "Vercel.png",
  "Vite.js.png",
];
